name: falcon
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.5 <3.0.0"
  # flutter: 3.3.3

dependencies:
  auto_size_text: ^3.0.0
  bloc: ^8.1.0
  cached_network_image: ^3.2.2
  clock: ^1.1.1
  equatable: ^2.0.5
  flex_color_scheme: ^6.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_cache_manager: ^3.3.0
  flutter_local_notifications: ^12.0.3
  flutter_native_timezone: ^2.0.0
  flutter_svg: ^1.1.6
  font_awesome_flutter: ^10.3.0
  go_router: ^5.2.1
  google_fonts: ^3.0.1
  google_maps_flutter: ^2.2.1
  hydrated_bloc: ^9.0.0
  intl: ^0.17.0
  live_activities: ^1.2.1
  path_provider: ^2.0.11
  spacex_info_repository:
    path: packages/spacex_info_repository
  timezone: ^0.9.0

dev_dependencies:
  bloc_test: ^9.1.0
  dart_code_metrics: ^4.19.2
  flutter_test:
    sdk: flutter
  icons_launcher: ^2.0.6
  import_sorter: ^4.6.0
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/map_styles/
    - assets/rockets/falcon_heavy/

  fonts:
    - family: D-DIN
      fonts:
        - asset: fonts/D-DIN.otf
        - asset: fonts/D-DIN-Bold.otf
          weight: 700
        - asset: fonts/D-DINCondensed.otf
          style: italic
        - asset: fonts/D-DINCondensed-Bold.otf
          weight: 700
          style: italic
