name: starcat
version: 1.0.0+2
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_animated: ^3.2.0
  auto_size_text: ^3.0.0
  bloc: ^8.1.2
  cached_network_image: ^3.3.0
  clock: ^1.1.1
  cupertino_icons: ^1.0.6
  duration: ^3.0.13
  dynamic_color: ^1.6.8
  equatable: ^2.0.5
  firebase_analytics: ^10.6.2
  firebase_core: ^2.20.0
  firebase_crashlytics: ^3.4.2
  firebase_messaging: ^14.7.2
  firebase_performance: ^0.9.3+2
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0
  flutter_bloc: ^8.1.3
  flutter_cache_manager: ^3.3.1
  flutter_native_timezone: ^2.0.0
  flutter_svg: ^2.0.8
  go_router: ^12.0.1
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.5.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.1.0
  hydrated_bloc: ^9.1.2
  intl: ^0.18.0
  json_annotation: ^4.8.1
  launch_library_repository:
    path: packages/launch_library_repository
  live_activities: ^1.8.0
  logger: ^2.0.2+1
  maps_launcher: ^2.2.0
  mockito: ^5.4.2
  notifications_repository:
    path: packages/notifications_repository
  # Temporary fix
  phosphor_flutter:
    git: https://github.com/phosphor-icons/flutter.git
  spaceflight_news_repository:
    path: packages/spaceflight_news_repository
  url_launcher: ^6.2.1
  vector_graphics: ^1.1.9
  very_good_infinite_list: ^0.7.1
  wiredash: ^1.7.5

dev_dependencies:
  bloc_test: ^9.1.5
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  json_serializable: ^6.7.1
  mocktail: ^1.0.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/map_styles/
    - assets/schematics/falcon_9/
    - assets/schematics/falcon_heavy/
