name: starcat
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0"

dependencies:
  app_settings: ^4.2.0
  auto_animated: ^3.1.0
  auto_size_text: ^3.0.0
  bloc: ^8.1.1
  cached_network_image: ^3.2.2
  clock: ^1.1.1
  cupertino_icons: ^1.0.5
  duration: ^3.0.12
  dynamic_color: ^1.6.5
  equatable: ^2.0.5
  flex_color_scheme: ^7.1.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1
  flutter_bloc: ^8.1.2
  flutter_cache_manager: ^3.3.0
  flutter_local_notifications: ^14.0.0+2
  flutter_native_timezone: ^2.0.0
  flutter_svg: ^2.0.5
  go_router: ^7.0.1
  google_fonts: ^4.0.4
  google_maps_flutter: ^2.2.5
  http: ^0.13.5
  hydrated_bloc: ^9.1.0
  intl: ^0.18.0
  json_annotation: ^4.8.0
  launch_library_repository:
    path: packages/launch_library_repository
  live_activities: ^1.7.4
  logger: ^1.3.0
  maps_launcher: ^2.2.0
  mockito: ^5.4.0
  path_provider: ^2.0.14
  phosphor_flutter: ^2.0.0
  share_plus: ^7.0.0
  sliver_tools: ^0.2.10
  spaceflight_news_repository:
    path: packages/spaceflight_news_repository
  timezone: ^0.9.2
  url_launcher: ^6.1.10
  vector_graphics: ^1.1.5
  wiredash: ^1.7.0
  workmanager: ^0.5.1

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.4.4
  dart_code_metrics: ^5.7.4
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  json_serializable: ^6.7.0
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/map_styles/
    - assets/schematics/falcon_9/
    - assets/schematics/falcon_heavy/
