name: falcon
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  bloc: ^8.1.1
  cached_network_image: ^3.2.2
  clock: ^1.1.1
  cupertino_icons: ^1.0.5
  dynamic_color: ^1.6.2
  equatable: ^2.0.5
  flex_color_scheme: ^7.0.0-dev.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.0
  flutter_bloc: ^8.1.2
  flutter_cache_manager: ^3.3.0
  flutter_local_notifications: ^13.0.0
  flutter_native_timezone: ^2.0.0
  flutter_svg: ^2.0.2
  go_router: ^6.2.0
  google_fonts: ^4.0.3
  google_maps_flutter: ^2.2.4
  hydrated_bloc: ^9.1.0
  intl: ^0.18.0
  live_activities: ^1.6.0
  maps_launcher: ^2.2.0
  path_provider: ^2.0.13
  phosphor_flutter: ^1.4.0
  space_devs_repository:
    path: packages/space_devs_repository
  timezone: ^0.9.0
  url_launcher: ^6.1.10
  vector_graphics: ^1.1.0

dev_dependencies:
  bloc_test: ^9.1.0
  dart_code_metrics: ^5.6.0
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/map_styles/
    - assets/schematics/falcon_9/
    - assets/schematics/falcon_heavy/
