name: starcat
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  auto_animated: ^3.1.0
  auto_size_text: ^3.0.0
  bloc: ^8.1.1
  cached_network_image: ^3.2.2
  clock: ^1.1.1
  cupertino_icons: ^1.0.5
  dynamic_color: ^1.6.3
  equatable: ^2.0.5
  flex_color_scheme: ^7.0.3
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1
  flutter_bloc: ^8.1.2
  flutter_cache_manager: ^3.3.0
  flutter_local_notifications: ^13.0.0
  flutter_native_timezone: ^2.0.0
  flutter_svg: ^2.0.5
  go_router: ^6.5.7
  google_fonts: ^4.0.3
  google_maps_flutter: ^2.2.5
  http: ^0.13.5
  hydrated_bloc: ^9.1.0
  intl: ^0.17.0
  json_annotation: ^4.8.0
  launch_library_repository:
    path: packages/launch_library_repository
  live_activities: ^1.7.3
  maps_launcher: ^2.2.0
  path_provider: ^2.0.14
  phosphor_flutter: ^2.0.0
  share_plus: ^6.3.2
  sliver_tools: ^0.2.9
  spaceflight_news_repository:
    path: packages/spaceflight_news_repository
  timezone: ^0.9.1
  url_launcher: ^6.1.10
  vector_graphics: ^1.1.5
  wiredash: ^1.6.0
  workmanager: ^0.5.1

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.3.3
  dart_code_metrics: ^5.7.2
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/map_styles/
    - assets/schematics/falcon_9/
    - assets/schematics/falcon_heavy/
