name: starcat
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  app_settings: ^5.0.0
  auto_animated: ^3.2.0
  auto_size_text: ^3.0.0
  bloc: ^8.1.2
  cached_network_image: ^3.2.2
  clock: ^1.1.1
  cupertino_icons: ^1.0.5
  duration: ^3.0.13
  dynamic_color: ^1.6.6
  equatable: ^2.0.5
  flex_color_scheme: ^7.2.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0
  flutter_bloc: ^8.1.3
  flutter_cache_manager: ^3.3.1
  flutter_local_notifications: ^15.1.0+1
  flutter_native_timezone: ^2.0.0
  flutter_svg: ^2.0.7
  go_router: ^10.0.0
  google_fonts: ^5.1.0
  google_maps_flutter: ^2.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.1.0
  hydrated_bloc: ^9.1.2
  intl: ^0.18.0
  json_annotation: ^4.8.1
  launch_library_repository:
    path: packages/launch_library_repository
  live_activities: ^1.7.4
  logger: ^2.0.1
  maps_launcher: ^2.2.0
  mockito: ^5.4.2
  path_provider: ^2.0.14
  phosphor_flutter: ^2.0.0
  sliver_tools: ^0.2.12
  spaceflight_news_repository:
    path: packages/spaceflight_news_repository
  timezone: ^0.9.2
  url_launcher: ^6.1.12
  vector_graphics: ^1.1.7
  very_good_infinite_list: ^0.7.0
  wiredash: ^1.7.2
  workmanager: ^0.5.1
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  bloc_test: ^9.1.3
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  json_serializable: ^6.7.1
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/map_styles/
    - assets/schematics/falcon_9/
    - assets/schematics/falcon_heavy/
