name: launch_library_api
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  http: ^1.1.0
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.3.2
  import_sorter: ^4.6.0
  json_serializable: ^6.6.1
  mocktail: ^1.0.0
  test: ^1.24.6
  very_good_analysis: ^5.1.0
