name: launch_library_repository
description: Dart package for fetching data from the Space Devs API
publish_to: none

environment:
  sdk: ">=3.0.0"

dependencies:
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  launch_library_api:
    path: ../launch_library_api

dev_dependencies:
  build_runner: ^2.4.4
  import_sorter: ^4.6.0
  json_serializable: ^6.6.2
  mocktail: ^0.3.0
  test: ^1.24.2
  very_good_analysis: ^4.0.0
