name: launch_library_repository
description: Dart package for fetching data from the Space Devs API
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  launch_library_api:
    path: ../launch_library_api

dev_dependencies:
  import_sorter: ^4.6.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0
