name: spaceflight_news_api
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  equatable: ^2.0.5
  http: ^1.1.0
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.6
  import_sorter: ^4.6.0
  json_serializable: ^6.5.2
  mocktail: ^0.3.0
  test: ^1.24.4
  very_good_analysis: ^5.0.0+1
