name: spacex_info_repository
description: Dart package for fetching data about SpaceX
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  spacex_api:
    path: ../spacex_api

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
