name: spaceflight_news_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  equatable: ^2.0.5
  spaceflight_news_api:
    path: ../spaceflight_news_api

dev_dependencies:
  import_sorter: ^4.6.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0
